// <auto-generated />
namespace Sigfaz.Infra.CrossCutting.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class IdentiMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdentiMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201801200117562_IdentiMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
